[package]
name = "genref"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
parking_lot = { version = "0.12.0", features = ["nightly"] }
ref_thread_local = "0.1.1"
 
[toolchain]
channel = "nightly"
